name: dinehub-api-cd

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.2.1
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v4.0.1
       with: 
         dotnet-version: 8.0.x
     - name: Restore dependencies
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore -c Release
     - name: Publish
       run: dotnet publish ./src/DineHub.Api/DineHub.Api.csproj -o ${{env.DOTNET_ROOT}}/api --no-build 
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.4.3
       with:
        name: api-artifact
        path: ${{env.DOTNET_ROOT}}/api
       
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
         name: api-artifact
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with: 
          app-name: dinehub-api-dev-2024
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
